server:
  port: 8086
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  jmx.default-domain: test
  datasource: # настройки источника данных (базы)
    username: user # логин для подключения к базе
    password: password # пароль для подключения к базе
    driverClassName: org.h2.Driver #драйвер для подключения к базе
    url: jdbc:h2:mem:mydb1 #url для подключения к базе
  liquibase:
    change-log: /db/changelog/changelog.yml
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      dialect: org.h2.Driver
      ddl-auto: update

registration:
  confirm:
    need: false
    url: "http://195.234.208.58:8086/api/v1/account/registration_complete"

external:
  vk:
    id: ENC(m7rHhgvZf1a3XykimmtX9A==)
    token: ENC(0FWZ/Ebbh5M0GV/ZD8TcXU1ISRbcusF9MrjiZsUnR4Vf4Hv8l7sp32S4w/KWqNsnLI7ppZCPy3ZztKJxXLGkhpBEkJXeEZpE6NFIDCts6BY=)
  cloudinary:
    cloud: ENC(Vfhff27NWtbJpMagmXDrAPdoUn5Wl0BP)
    key: ENC(Dw9PMgrkxd0Q7YTIBowaLFI/ixt2nvHf)
    secret: ENC(hQVnqsRAm3jW1tjWc3zDAOu19ppToSJ7czBD5CHa0E6coGq36y7wVA==)
  mail:
    key: ENC(cbiIlGM7COCT2LWMVF8KHGK51r+I+M2yvPUwbrQBo+FP6qYiSXqJEgIpH0DeWqet)
    secret: ENC(ej/k4xIoS2SQYjlcvgMdMjJ5nYNkYWijRoaBtknf+UWeBB5UETd1yRO0GA9udfEg)
    from: ENC(pJ86R3iKC6yiWVTA3UOSQXiSyFWgWQ2NcwrY6fcCEVo=)

jasypt:
  encryptor:
    bean: encryptorBean

cors:
  - http://localhost/